services:
  postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "${DB_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - happy_network
      restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    networks:
      - happy_network

  happy_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: happy_bot_container
    depends_on:
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
    ports:
      - "8000:8000" 
    networks:
      - happy_network

volumes:
  postgres_data:
    driver: local

networks:
  happy_network:
    driver: bridge